sonar.projectKey=VishakhGaitonde_schema-insight
sonar.organization=vishakhgaitonde
sonar.projectName=SchemaInsight
sonar.projectVersion=1.0
sonar.sources=backend/src
sonar.tests=backend/tests
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.exclusions=**/node_modules/**